### ISSUE TITLE
Stardust DS hub/launcher

### ISSUE THREAD

**Issue by ghost** [Yackerw/StarDust-DS#1]
Open source engines have their own launcher. in this launcher you can start your project with the 3d engine so that games can be accessible to make this way

**Comment by Yackerw** [comment]
Are you suggesting an editor like Unity, Godot, Unreal, etc have? That'd be an interesting proposition. It is somewhat worth noting though, that StarDust's actual functionality of "scenes" that you'd expect from those sorts of engines is actually very limited. There's no actual "core" idea of a "scene" (unless this was tacked on as part of the editor, which would be doable) and what you can actually do with an individual object is pretty limited. There's no parent-child structure (due to the fact that the DS would probably have a minor stroke if you abused this at all) and, rather than objects being nebulous blobs of data that can have code attached, the code it executes more-or-less determines the object.

There's also an implicit expectation of asset management with this. Which...on the DS, is not great. Loading assets in and out of RAM as you need them suddenly becomes harder, and then there's an implicit understanding that it'd handle most asset loading for you, which would likely end up with said asset loading being much less efficient.

It wouldn't be impossible, but you'd likely to have to do a lot of leg work yourself, and it still wouldn't be the same paradigm as you'd expect from other engines. While it could help you automatically define objects and place them, you'd have to manually set visuals for many object types that wouldn't automatically correlate in game, while there'd have to be support for certain object types that can change what their visuals are AND have that correlate in game...it'd also be somewhat difficult to be able to get custom variables to objects be editable in editor. It might just end up being confusing to use, unfortunately.
